# Generated by Django 5.0.2 on 2024-03-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('equipo_local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_local', to='App.equipos')),
                ('equipo_visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_visitante', to='App.equipos')),
            ],
        ),
    ]
